# models/enums.py
from enum import Enum

class EntryTiming(Enum):
    IMMEDIATE = "ENTRADA INMEDIATA"
    WAIT_DIP = "ESPERAR RETROCESO"
    WAIT_BREAKOUT = "ESPERAR RUPTURA"
    WAIT_CONSOLIDATION = "ESPERAR CONSOLIDACIÓN"
    NOT_RECOMMENDED = "ENTRADA NO RECOMENDADA"

class TradingSignal(Enum):
    BUY = "COMPRAR"
    SELL = "VENDER"
    HOLD = "MANTENER"

class MarketTrend(Enum):
    STRONG_UPTREND = "FUERTE TENDENCIA ALCISTA"
    UPTREND = "TENDENCIA ALCISTA"
    NEUTRAL = "NEUTRAL"
    DOWNTREND = "TENDENCIA BAJISTA"
    STRONG_DOWNTREND = "FUERTE TENDENCIA BAJISTA"

class SignalStrength(Enum):
    STRONG = "FUERTE"
    MODERATE = "MODERADA"
    WEAK = "DÉBIL"
